#!/bin/bash

help() {
  echo "Use LTS Version"
  echo ""
  echo "Usage:"
  echo "  zdvm lts"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "Use LTS Version $PLUGIN_DVM_DENO_LTS_VERSION"

  nvm::use $PLUGIN_DVM_DENO_LTS_VERSION
}

run() {
  core $@
}

run $@
